/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BorderColors: typeof import('./../.vitepress/theme/components/colors/BorderColors.vue')['default']
    Card: typeof import('./../.vitepress/theme/components/home/Card.vue')['default']
    Color: typeof import('./../.vitepress/theme/components/theme-editor/Color.vue')['default']
    ColorGroup: typeof import('./../.vitepress/theme/components/colors/ColorGroup.vue')['default']
    ComponentOverview: typeof import('./../.vitepress/theme/components/ComponentOverview.vue')['default']
    CustomUsageBlock: typeof import('./../.vitepress/theme/components/blocks/CustomUsageBlock.vue')['default']
    DemoBlock: typeof import('./../.vitepress/theme/components/blocks/DemoBlock.vue')['default']
    DemoBox: typeof import('./../.vitepress/theme/components/blocks/DemoBox.vue')['default']
    DocumentContent: typeof import('./../.vitepress/theme/components/DocumentContent.vue')['default']
    DocumentHeader: typeof import('./../.vitepress/theme/components/DocumentHeader.vue')['default']
    DocumentMobileDock: typeof import('./../.vitepress/theme/components/DocumentMobileDock.vue')['default']
    EcosystemList: typeof import('./../.vitepress/theme/components/EcosystemList.vue')['default']
    Font: typeof import('./../.vitepress/theme/components/theme-editor/Font.vue')['default']
    Home: typeof import('./../.vitepress/theme/components/home/Home.vue')['default']
    Index: typeof import('./../.vitepress/theme/components/theme-editor/Index.vue')['default']
    KongMing: typeof import('./../.vitepress/theme/components/home/KongMing.vue')['default']
    LayoutColors: typeof import('./../.vitepress/theme/components/colors/LayoutColors.vue')['default']
    PaletteColors: typeof import('./../.vitepress/theme/components/colors/PaletteColors.vue')['default']
    Placeholder: typeof import('./../.vitepress/theme/components/Placeholder.vue')['default']
    Preset: typeof import('./../.vitepress/theme/components/theme-editor/Preset.vue')['default']
    Size: typeof import('./../.vitepress/theme/components/theme-editor/Size.vue')['default']
    StatusColors: typeof import('./../.vitepress/theme/components/colors/StatusColors.vue')['default']
    TextColors: typeof import('./../.vitepress/theme/components/colors/TextColors.vue')['default']
    UsageBlock: typeof import('./../.vitepress/theme/components/blocks/UsageBlock.vue')['default']
    WBFooter: typeof import('./../.vitepress/theme/components/home/WBFooter.vue')['default']
    WBHeader: typeof import('./../.vitepress/theme/components/home/WBHeader.vue')['default']
    WBHeaderMenu: typeof import('./../.vitepress/theme/components/home/WBHeaderMenu.vue')['default']
  }
}
