/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurCard: typeof import('./../.vitepress/theme/components/awesome/BlurCard.vue')['default']
    Card: typeof import('./../.vitepress/theme/components/tools/Card.vue')['default']
    ChangelogsBlock: typeof import('./../.vitepress/theme/components/blocks/ChangelogsBlock.vue')['default']
    CustomUsageBlock: typeof import('./../.vitepress/theme/components/blocks/CustomUsageBlock.vue')['default']
    DemoBlock: typeof import('./../.vitepress/theme/components/blocks/DemoBlock.vue')['default']
    Placeholder: typeof import('./../.vitepress/theme/components/tools/Placeholder.vue')['default']
    UsageBlock: typeof import('./../.vitepress/theme/components/blocks/UsageBlock.vue')['default']
  }
}
