name: coverage

on:
  push:
    tags:
      - 'v*'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build coverage reports
        run: |
          pnpm --filter=@ephemeras/fs test:coverage

      # Push packages reports
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: fs
          files: ./packages/fs/coverage/coverage-final.json
